// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7gvdeSXu5zYJHEAky7U9IQ6Jwe9VOb0',
    appId: '1:338052593639:web:b4cec1513b6851883fef42',
    messagingSenderId: '338052593639',
    projectId: 'jobquest-aed68',
    authDomain: 'jobquest-aed68.firebaseapp.com',
    storageBucket: 'jobquest-aed68.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVOjnRR2vTlZzNl8SB5j4u0r5xz-RbZs',
    appId: '1:338052593639:android:132ef0e6a4368c5f3fef42',
    messagingSenderId: '338052593639',
    projectId: 'jobquest-aed68',
    storageBucket: 'jobquest-aed68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHT-N2EHIhve68vgkuUxx8cDBMyyvN1lc',
    appId: '1:338052593639:ios:d4712f3b042d61713fef42',
    messagingSenderId: '338052593639',
    projectId: 'jobquest-aed68',
    storageBucket: 'jobquest-aed68.appspot.com',
    iosBundleId: 'com.example.jobquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHT-N2EHIhve68vgkuUxx8cDBMyyvN1lc',
    appId: '1:338052593639:ios:d4712f3b042d61713fef42',
    messagingSenderId: '338052593639',
    projectId: 'jobquest-aed68',
    storageBucket: 'jobquest-aed68.appspot.com',
    iosBundleId: 'com.example.jobquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL7gvdeSXu5zYJHEAky7U9IQ6Jwe9VOb0',
    appId: '1:338052593639:web:40d803f7b3b7eeb23fef42',
    messagingSenderId: '338052593639',
    projectId: 'jobquest-aed68',
    authDomain: 'jobquest-aed68.firebaseapp.com',
    storageBucket: 'jobquest-aed68.appspot.com',
  );
}
